// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPs_X3H3Kgo3lBhCoxAyjZv7BDIPUW5k4',
    appId: '1:220567878097:web:bcaf25c4ec48119df448f0',
    messagingSenderId: '220567878097',
    projectId: 'es2023',
    authDomain: 'es2023.firebaseapp.com',
    storageBucket: 'es2023.appspot.com',
    measurementId: 'G-4JL2DLFSXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8RkeoV025_u8VPK6_dY57lxShW8VNg70',
    appId: '1:220567878097:android:958ac202174ac7a9f448f0',
    messagingSenderId: '220567878097',
    projectId: 'es2023',
    storageBucket: 'es2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6yNhThFfZYatAlNPbKl88TaMWo5Ohgs',
    appId: '1:220567878097:ios:b272339aabeab8a5f448f0',
    messagingSenderId: '220567878097',
    projectId: 'es2023',
    storageBucket: 'es2023.appspot.com',
    iosClientId: '220567878097-s98k9edqvv6so1lte2sadfh4j85l313t.apps.googleusercontent.com',
    iosBundleId: 'com.example.es',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH6yNhThFfZYatAlNPbKl88TaMWo5Ohgs',
    appId: '1:220567878097:ios:b272339aabeab8a5f448f0',
    messagingSenderId: '220567878097',
    projectId: 'es2023',
    storageBucket: 'es2023.appspot.com',
    iosClientId: '220567878097-s98k9edqvv6so1lte2sadfh4j85l313t.apps.googleusercontent.com',
    iosBundleId: 'com.example.es',
  );
}
