name: Unit tests

on:
  push:
    branches:
      - main

jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
      working-directory: app

