name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  drive:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.8'
        channel: "stable"
    - run: flutter pub get
      working-directory: app
    - run: flutter test
      working-directory: app


#    steps:
#    
#    - uses: actions/checkout@v2
#    - uses: actions/setup-java@v1
#      with:
#        java-version: "12.x"
#    - uses: subosito/flutter-action@v1
#      with:
#        channel: "stable"
#    - run: flutter test
#      working-directory: app


